### ISSUE TITLE
anytemplate_cli fails if LANG (locale) is not set suc like in docker

### ISSUE THREAD

**Issue by ssato** [ssato/python-anytemplate#3]
Typical example.

```
[root@e8e4a85c5bb4 /]# anytemplate_cli -E jinja2 /usr/share/fleure/templates/2/ja/rpm_depgraph_gv.dot.j2 -C test/out/rpm_depgraph_gv.jso
n  -v -o /tmp/t.dot
Traceback (most recent call last):
  File "/usr/bin/anytemplate_cli", line 11, in <module>
    load_entry_point('anytemplate==0.1.2', 'console_scripts', 'anytemplate_cli')()
  File "/usr/lib/python2.7/site-packages/anytemplate/cli.py", line 104, in main
    at_engine=options.engine, at_ask_missing=True)
  File "/usr/lib/python2.7/site-packages/anytemplate/api.py", line 175, in render_to
    res = render(filepath, context=context, **options)
  File "/usr/lib/python2.7/site-packages/anytemplate/api.py", line 151, in render
    return _render(filepath=filepath, context=context, **options)
  File "/usr/lib/python2.7/site-packages/anytemplate/api.py", line 107, in _render
    raise CompileError("exc=%r, template=%s" % (exc, target[:200]))
anytemplate.globals.CompileError: exc=AttributeError("'NoneType' object has no attribute 'lower'",), template=/usr/share/fleure/templates/2/ja/rpm_depgraph_gv.dot.j2
[root@e8e4a85c5bb4 /]# python
Python 2.7.14 (default, Nov  3 2017, 10:55:25)
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getdefaultlocale()
(None, None)
>>>
[root@e8e4a85c5bb4 /]# echo $LANG

[root@e8e4a85c5bb4 /]#
```

**Comment by ssato** [comment]
2cf4d24 may close this.
