### ISSUE TITLE
Jinja2.loaders does not expose method 'open_if_exists'

### ISSUE THREAD

**Issue by jorgeegomez** [ssato/python-anytemplate#9]
When trying to use the Jinja2 engine, in python 3.12, I'm getting this error:
```
Traceback (most recent call last):
  File "/home/user/.venv/wiki/lib/python3.12/site-packages/anytemplate/api.py", line 85, in _render
    return render_fn(target, context=context, at_paths=at_paths,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.venv/wiki/lib/python3.12/site-packages/anytemplate/engines/base.py", line 235, in render
    return self.render_impl(template, context, at_paths=paths,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.venv/wiki/lib/python3.12/site-packages/anytemplate/engines/jinja2.py", line 200, in render_impl
    return self._render(os.path.basename(template), context, True, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.venv/wiki/lib/python3.12/site-packages/anytemplate/engines/jinja2.py", line 155, in _render
    tmpl = (env.get_template if is_file else env.from_string)(template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.venv/wiki/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.venv/wiki/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.venv/wiki/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.venv/wiki/lib/python3.12/site-packages/anytemplate/engines/jinja2.py", line 81, in get_source
    contents_mtimes = list(_load_file_itr(files, self.encoding))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.venv/wiki/lib/python3.12/site-packages/anytemplate/engines/jinja2.py", line 49, in _load_file_itr
    fileobj = jinja2.loaders.open_if_exists(filename)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'jinja2.loaders' has no attribute 'open_if_exists'
```

The method seems to be exposed by `jinja2.utils` instead.

**Comment by ssato** [comment]
@jorgeegomez Thanks for your report! I'll look into this asap.
